package com.wedding.venue.model;

import jakarta.persistence.*; // Import all necessary JPA annotations

@Entity // Marks this class as a JPA entity
@Table(name = "venues") // Maps this entity to a database table named 'venues'
public class Venue {
    @Id // Marks 'id' as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures ID to be auto-incremented by the database
    private Long id; // Changed ID type to Long

    private String name;
    private String location;
    private boolean available; // This field represents general availability

    // Default constructor is required by JPA
    public Venue() {}

    // Constructor for creating new Venues without an ID (ID will be generated by the DB)
    public Venue(String name, String location, boolean available) {
        this.name = name;
        this.location = location;
        this.available = available;
    }

    // Full constructor (useful for fetching from DB, but not for new entity creation)
    public Venue(Long id, String name, String location, boolean available) {
        this.id = id;
        this.name = name;
        this.location = location;
        this.available = available;
    }

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }
    public boolean isAvailable() { return available; }
    public void setAvailable(boolean available) { this.available = available; }

    @Override
    public String toString() {
        return "Venue{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", location='" + location + '\'' +
                ", available=" + available +
                '}';
    }
}