package com.wedding.venue.model;

import jakarta.persistence.*; // Import all necessary JPA annotations

@Entity // Marks this class as a JPA entity
@Table(name = "venues", schema = "dbo") // Maps this entity to a database table named 'venues'
public class Venue {
    @Id // Marks 'id' as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures ID to be auto-incremented by the database
    private Long id; // Changed ID type to Long

    private String name;
    private String location;
    private boolean available; // This field represents general availability

    // --- NEWLY ADDED FIELDS ---
    @Column(name = "images") // Explicitly map to 'images' column
    private String images;

    @Column(name = "price") // Explicitly map to 'price' column
    private Double price; // Use Double for monetary values

    private Integer capacity; // Capacity for guests
    private Integer rating;   // Rating out of 5

    // Default constructor is required by JPA
    public Venue() {}

    // Constructor for creating new Venues without an ID (ID will be generated by the DB)
    public Venue(String name, String location, boolean available, String images, Double price, Integer capacity, Integer rating) {
        this.name = name;
        this.location = location;
        this.available = available;
        this.images = images;
        this.price = price;
        this.capacity = capacity;
        this.rating = rating;
    }

    // Full constructor (useful for fetching from DB, but not for new entity creation)
    public Venue(Long id, String name, String location, boolean available, String images, Double price, Integer capacity, Integer rating) {
        this.id = id;
        this.name = name;
        this.location = location;
        this.available = available;
        this.images = images;
        this.price = price;
        this.capacity = capacity;
        this.rating = rating;
    }

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }
    public boolean isAvailable() { return available; }
    public void setAvailable(boolean available) { this.available = available; }

    // --- NEWLY ADDED GETTERS AND SETTERS ---
    public String getImages() { return images; }
    public void setImages(String images) { this.images = images; }

    public Double getPrice() { return price; }
    public void setPrice(Double price) { this.price = price; }

    public Integer getCapacity() { return capacity; }
    public void setCapacity(Integer capacity) { this.capacity = capacity; }

    public Integer getRating() { return rating; }
    public void setRating(Integer rating) { this.rating = rating; }

    @Override
    public String toString() {
        return "Venue{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", location='" + location + '\'' +
                ", available=" + available +
                ", images='" + images + '\'' +
                ", price=" + price +
                ", capacity=" + capacity +
                ", rating=" + rating +
                '}';
    }
}